import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router'; import { useSafeAreaInsets } from 'react-native-safe-area-context'; import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../src/theme/colors'; import { spacing } from '../../src/theme/spacing'; import { typography, fontFamily } from '../../src/theme/typography';
const PRIVACY=`Last updated: July 2026\n\nFine Glaze COS is an internal construction operations app used by Fine Glaze employees, supervisors, owners and approved clients.\n\nWhat we collect\n- Account details: name, phone number, role\n- Attendance: GPS location and a selfie photo at punch-in, used only to verify you are on site\n- Work records: daily progress reports, photos/videos of site work, tasks, and material requests\n- Documents you upload: drawings, invoices, contracts and similar files\n- Device push notification token, used only to deliver in-app alerts\n\nHow we use it\nData is used solely to run day-to-day site operations — attendance, task tracking, reporting, approvals, payments and communication between your team and clients. We do not sell or share your data with third parties for advertising.\n\nWho can see it\nAccess is restricted by role. Workers see their own records; supervisors see their assigned sites; owners and admins see company-wide data as configured under Roles & Permissions. Clients only see projects and approvals shared with their organisation.\n\nStorage & retention\nData is stored securely in Fine Glaze's Supabase database and storage buckets, hosted in the ap-southeast-1 region. Company owners can request a full data export or deletion by contacting Fine Glaze support.\n\nContact\nFor privacy questions, contact your company administrator or Fine Glaze support.`;
const TERMS=`Last updated: July 2026\n\nBy using Fine Glaze COS you agree to:\n\n1. Use the app only for legitimate Fine Glaze business — attendance, reporting, communication and project management.\n2. Keep your login credentials confidential. You are responsible for activity under your account.\n3. Submit accurate attendance, DPRs and material requests. Falsified records may result in disciplinary action.\n4. Location data is only captured during punch-in/out for attendance verification, not tracked continuously.\n5. Uploaded photos, videos and documents become part of the project record and may be shared with relevant team members and clients per your role's permissions.\n6. Fine Glaze may suspend accounts that misuse the app or violate company policy.\n7. The app is provided for internal company use; features and screens may change as the app is improved.\n\nFor questions about these terms, contact your company administrator.`;
export default function LegalScreen(){const router=useRouter();const insets=useSafeAreaInsets();const{doc}=useLocalSearchParams<{doc?:string}>();const isPrivacy=doc!=='terms';const content=isPrivacy?PRIVACY:TERMS;
return <View style={[styles.container,{paddingTop:insets.top+spacing.md}]}><View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color={colors.ink}/></TouchableOpacity><Text style={styles.title}>{isPrivacy?'Privacy Policy':'Terms of Service'}</Text><View style={{width:24}}/></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.body}>{content}</Text></ScrollView></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{height:56,paddingHorizontal:spacing.lg,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{...typography.h4,color:colors.ink},content:{padding:spacing.lg,paddingBottom:spacing['5xl']},body:{...typography.bodySmall,color:colors.neutral[700],lineHeight:22}});
