import React, { useState } from 'react';
import { Alert, Share, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import QRCode from 'react-native-qrcode-svg';
import { useQuery } from '@tanstack/react-query';
import { Card } from '../../src/components';
import { supabase } from '../../src/lib/supabase';
import { colors } from '../../src/theme/colors';
import { spacing, radius } from '../../src/theme/spacing';
import { typography, fontFamily } from '../../src/theme/typography';
import { showAlert } from '../../src/utils/alert';

export default function ProjectQrScreen() {
 const router=useRouter(); const insets=useSafeAreaInsets(); const params=useLocalSearchParams<{projectId?:string}>(); const [selected,setSelected]=useState(params.projectId || '');
 const {data:projects=[]}=useQuery({queryKey:['projects'],queryFn:async()=>{const{data,error}=await supabase.from('projects').select('id,name,address,city').neq('status','completed').order('name');if(error)throw error;return data||[];}});
 const project=projects.find((p:any)=>p.id===selected); const value=project?`fineglaze://project/${project.id}`:'';
 const share=async()=>{if(!project)return;await Share.share({message:`Fine Glaze COS — ${project.name}\nOpen project: ${value}`});};
 return <View style={[styles.container,{paddingTop:insets.top+spacing.md}]}><View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color={colors.ink}/></TouchableOpacity><Text style={styles.title}>Project QR Code</Text><TouchableOpacity onPress={share} disabled={!project}><Ionicons name="share-outline" size={24} color={project?colors.primary:colors.neutral[300]}/></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.label}>Select Project</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.projectScroll}>{projects.map((p:any)=><TouchableOpacity key={p.id} onPress={()=>setSelected(p.id)} style={[styles.chip,selected===p.id&&styles.chipActive]}><Text style={[styles.chipText,selected===p.id&&styles.chipTextActive]}>{p.name}</Text></TouchableOpacity>)}</ScrollView>{project?<Card style={styles.qrCard}><View style={styles.logo}><Text style={styles.logoText}>FG</Text></View><Text style={styles.projectName}>{project.name}</Text><Text style={styles.address}>{project.address||project.city||'Fine Glaze project'}</Text><View style={styles.qrWrap}><QRCode value={value} size={220} color={colors.ink} backgroundColor={colors.white}/></View><Text style={styles.scanText}>Scan with Fine Glaze COS to open this project</Text><View style={styles.actions}><TouchableOpacity style={styles.action} onPress={share}><Ionicons name="share-social" size={20} color={colors.primary}/><Text style={styles.actionText}>Share</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={()=>showAlert('Print QR','Use Share to send this QR link for printing at the site office.')}><Ionicons name="print" size={20} color={colors.primary}/><Text style={styles.actionText}>Print</Text></TouchableOpacity></View></Card>:<Card style={styles.empty}><Ionicons name="qr-code-outline" size={48} color={colors.primary}/><Text style={styles.emptyTitle}>Choose a project</Text><Text style={styles.emptyText}>A secure project QR will appear here.</Text></Card>}<Card style={styles.info}><Ionicons name="shield-checkmark" size={22} color={colors.success}/><Text style={styles.infoText}>The QR contains only the project ID. Users still need to sign in and must have project access.</Text></Card></ScrollView></View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{height:56,paddingHorizontal:spacing.lg,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{...typography.h4,color:colors.ink},content:{padding:spacing.lg,paddingBottom:spacing['5xl']},label:{...typography.bodySmall,fontFamily:fontFamily.medium,color:colors.ink,marginBottom:spacing.sm},projectScroll:{marginBottom:spacing.xl},chip:{paddingHorizontal:spacing.md,paddingVertical:10,borderRadius:radius.full,backgroundColor:colors.neutral[100],borderWidth:1,borderColor:colors.neutral[200],marginRight:spacing.sm},chipActive:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{...typography.caption,color:colors.neutral[700]},chipTextActive:{color:colors.white},qrCard:{padding:spacing.xl,alignItems:'center'},logo:{width:48,height:48,borderRadius:12,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},logoText:{...typography.h5,color:colors.white},projectName:{...typography.h4,color:colors.ink,marginTop:spacing.md,textAlign:'center'},address:{...typography.bodySmall,color:colors.neutral[500],textAlign:'center',marginTop:4},qrWrap:{padding:spacing.lg,backgroundColor:colors.white,borderWidth:1,borderColor:colors.neutral[200],marginVertical:spacing.xl},scanText:{...typography.bodySmall,color:colors.neutral[600],textAlign:'center'},actions:{flexDirection:'row',gap:spacing.md,marginTop:spacing.xl},action:{minWidth:110,height:48,borderRadius:radius.md,backgroundColor:colors.tertiary+'22',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.sm},actionText:{...typography.bodySmall,fontFamily:fontFamily.semiBold,color:colors.primary},empty:{padding:spacing['3xl'],alignItems:'center',gap:spacing.sm},emptyTitle:{...typography.h5,color:colors.ink},emptyText:{...typography.bodySmall,color:colors.neutral[500]},info:{padding:spacing.lg,marginTop:spacing.lg,flexDirection:'row',gap:spacing.md},infoText:{flex:1,...typography.bodySmall,color:colors.neutral[600]}});
